Initial commit
RadicalImaging/M-Cornerstone3D pull request #8
Opened 2023-12-13 19:29 UTC by rodrigobasilio2022

### Context

### Changes & Results

### Testing

### Checklist

#### PR

- [] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [] My code has been well-documented (function documentation, inline comments,
  etc.)

- [] I have run the `yarn build:update-api` to update the API documentation, and have
  committed the changes to this PR. (Read more here https://www.cornerstonejs.org/docs/contribute/update-api)

#### Public Documentation Updates

- [] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [] "OS: 
- [] "Node version: 
- [] "Browser:
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

2023-12-27 19:53 UTC, ladeirarodolfo requested changes
Few comments only. Thanks for your PR

2023-12-27 19:53 UTC, ladeirarodolfo commented on packages/core/src/RenderingEngine/RenderingEngine.ts
> +  private continuousDrawing = false;
We need to scale a bit more RenderingEngine as far as this variable is concerned, as well _getScreenEventPositionFor from renderWindow. For that:
 
Create a RenderingEngine Configuration.
Consider the configuration schema
{
continuousDrawing: boolean
interactorConfiguration: {
  initialValue: {
      _getScreenEventPositionFor: Function
  },
  onInteraction: {
      [mapperConfiguration]: {
      },// this will work as being static mapper configuration
      [getMapperConfigurationCallback]: () => {} // this allows us for changing mapper configuration on the fly from OHIF
  }
}

2023-12-27 19:53 UTC, ladeirarodolfo commented on packages/core/src/RenderingEngine/RenderingEngine.ts
> +  public changeContinuousDrawingState(newState: boolean) {
Use the convention set and get

Add the get method

2023-12-27 19:53 UTC, ladeirarodolfo commented on packages/core/src/RenderingEngine/vtkClasses/vtkOffscreenMultiRenderWindow.js
> +  function _getScreenEventPositionFor(source) {
Add Code Documentation

2024-02-20 13:34 UTC, rodrigobasilio2022 commented
Closed as this repo will be updated with OSS

2024-02-20 13:34 UTC, closed without merging